config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: 'users/sessions' }

  root 'tests#index'

  resources :tests, only: :index do
    resources :questions, shallow: true, except: [:index], only: :show do
      resources :answers, shallow: true, except: [:index], only: :show
    end

    post :start, on: :member
  end
  resources :badges, only: [:show, :index]

  resources :test_passages, only: [:show, :update] do
    get :result, on: :member
    resources :gists, shallow: true, only: [:create]
    ##post :gist, on: :member
  end

  namespace :admin do
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true, except: [:index]
      end
    end
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :rule

  has_many :users_badges, dependent: :delete_all
  has_many :users, through: :users_badges

  validates :title, presence: true
  validates :url_icon, presence: true, url: true

  def get_name_of_param
    rule.params_type.constantize&.find_by(id: rule_value)&.title || rule_value
  end

  def user_badge_status(current_user_id)
    users_badges.where(user_id: current_user_id).count >= 1 ? "achieved" : "not achieved"
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_badge, only: [:show, :destroy, :update, :edit]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :url_icon, :rule_id, :rule_value)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end

  def show
    @badge = Badge.find(params[:id])
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= link_to 'Icon', badge.url_icon.html_safe, target: '_blank' %></td>
  <td><%= badge.rule.title %></td>
  <td><%= badge.get_name_of_param %></td>
  <td><%= link_to 'Show', admin_badge_path(badge) %></td>
  <td><%= link_to 'Edit',
                  edit_admin_badge_path(badge) %></td>
  <td><%= link_to 'Delete',
                  admin_badge_path(badge),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badge_title %><br>
  </p>

  <p>
    <%= form.label :url_icon %><br>
    <%= form.text_field :url_icon, id: :badge_path_icon %><br>
  </p>
  <p class="badge-rule">
    <%= form.label :rule_id %><br>
    <%= form.collection_select :rule_id, Rule.all, :id, :title, prompt: true %><br>
  </p>

  <p class="badge-field-test hide">
    <%= form.label :rule_value %><br>
    <%= form.collection_select :rule_value, Test.all, :id, :title, prompt: true %><br>
  </p>

  <p class="badge-field-category hide">
    <%= form.label :rule_value %><br>
    <%= form.collection_select :rule_value, Category.all, :id, :title, prompt: true %><br>
  </p>

  <p class="badge-field-level hide">
    <%= form.label :rule_value %><br>
    <%= form.number_field :rule_value, in: 0..100, step: 1, prompt: true %><br>
  </p>
  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Update badge</h1>
<%= render 'form' %>
<p>
  <%= link_to "Back", admin_badges_path %>
</p>

app/views/admin/badges/index.html.erb
<h1>All badges</h1>
<p>
  <%= link_to 'New badge', new_admin_badge_path %>
</p>

<%= render 'shared/errors', resource: @badge %>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Icon</th>
    <th>Rule title</th>
    <th>Rule attribute</th>
    <th colspan="3">Actions</th>
    <%= render @badges %>
</table>
<p>
  <%= link_to "Back", admin_tests_path %>
</p>

app/views/admin/badges/new.html.erb
<h1>Create new badge</h1>
<%= render 'form' %>
<p>
  <%= link_to "Back", admin_tests_path %>
</p>

app/views/admin/badges/show.html.erb
<p>Title  <%= @badge.title %></p>
<p>Icon  <%= link_to 'Icon', @badge.url_icon.html_safe, target: '_blank' %></p>
<p>Rule <%= @badge.rule.title %></p>
<p>Rule attribute <%= @badge.get_name_of_param %></p>

<p>
  <%= link_to 'Edit', edit_admin_badge_path(@badge) %>
</p>
<p>
  <%= link_to "Back", admin_badges_path %>
</p>