config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }, controllers: { sessions: 'users/sessions' }

  root 'tests#index'

  resources :tests, only: :index do
    resources :questions, shallow: true, except: [:index], only: :show do
      resources :answers, shallow: true, except: [:index], only: :show
    end

    post :start, on: :member
  end
  resources :badges, only: [:show, :index]

  resources :test_passages, only: [:show, :update] do
    get :result, on: :member
    resources :gists, shallow: true, only: [:create]
    ##post :gist, on: :member
  end

  namespace :admin do
    resources :badges, shallow: true
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: [:index] do
        resources :answers, shallow: true, except: [:index]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question
  SUCCESS_RATIO = 85.0

  def completed?
    current_question.nil?
  end

  def successful?
    result_calculation >= SUCCESS_RATIO
  end

  def accept!(answer_ids)
    if test.timer.present? && timer_calculating > time_for_test_passage
      current_question = nil
    else
      if correct_answer?(answer_ids)
        self.correct_questions += 1
      end
    end
    save!
  end

  def number_of_questions
    test.questions.count
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def result_calculation
    (correct_questions.to_d / test.questions.count.to_d) * 100
  end

  def timer_calculating
    DateTime.current.to_time - created_at
  end

  def time_for_test_passage
    test.timer.present? ? test.timer * 60 : "unlimited time"
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id>?', current_question.id).first
    end
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test_passage, only: [:show, :result, :update]

  def show
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      TestsMailer.completed_test(@test_passage).deliver_now
      UsersBadgesService.new(@test_passage).call
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= @test_passage.test.title %> was completed</h1>
<% if @test_passage.successful? %>
  <p style="color:green;">
    <%= @test_passage.result %>%
  </p>
<% else %>
  <p style="color:red;">
    <%= @test_passage.result %>%
  </p>
<% end %>
<p>
  <%= link_to 'All tests', tests_path %>
</p>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>

<p>
  <b><%= @test_passage.current_question.body %></b>
</p>
<p>
  Question number <%= @test_passage.current_question_number %> of <%= @test_passage.number_of_questions %>
</p>
<%= content_tag :div,
                '',
                class: 'timer-progress',
                data: { time_since_start: @test_passage.timer_calculating,
                        time_for_test: @test_passage.time_for_test_passage } %>
<div class="test-progress-back-ground">
  <%= content_tag :div,
                  'Progress',
                  class: 'test-passage-progress',
                  data: { number_current_question: @test_passage.current_question_number,
                          number_of_questions: @test_passage.number_of_questions } %>
</div>


<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body,
                                  include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p><%= link_to 'GistQuestion', test_passage_gists_path(@test_passage), method: :post %></p>
  <p><%= form.submit 'Next' %></p>
<% end %>